state.photos ||= {};state.groups ||= {};state.profiles.forEach(n=>state.groups[n]||='Sonstige');
const avatar=n=>state.photos[n]?`<img class="avatar" src="${state.photos[n]}" alt="">`:'👤';
const total=n=>Object.entries(state.done[n]||{}).reduce((s,[k,v])=>v?s+(exercise[+k.split('-').pop()]?.[2]||0):s,0);
const groupOrder=['U12.1','U14.1','Eltern','Sonstige'];
const baseRender=render;render=function(){baseRender();const groups=groupOrder.map(g=>{const members=[...state.profiles].filter(n=>state.groups[n]===g).sort((a,b)=>total(b)-total(a));return members.length?`<section class="rank-group"><h3>${g}</h3>${members.map((n,i)=>`<div class="rank"><b>${i+1}.</b>${avatar(n)}<strong>${n}</strong><strong>${total(n)} P</strong></div>`).join('')}</section>`:''}).join('');$('#ranking').innerHTML=groups;$('#profileButton span').innerHTML=`${avatar(state.active)} ${state.active}`};
const baseProfiles=profiles;profiles=function(){baseProfiles();$('#photoName').textContent=state.active;$('#groupSelect').value=state.groups[state.active]||'Sonstige';document.querySelectorAll('.profile-row button').forEach(b=>b.innerHTML=`${avatar(b.dataset.name)} <span>${b.dataset.name}<small>${state.groups[b.dataset.name]||'Sonstige'}</small></span>`)};
$('#groupSelect').onchange=e=>{state.groups[state.active]=e.target.value;store();profiles();render()};
$('#addProfile').onclick=()=>{const n=$('#newProfile').value.trim();if(n&&!state.profiles.includes(n)){state.profiles.push(n);state.active=n;state.groups[n]=$('#newGroup').value;$('#newProfile').value='';store();profiles();render()}};
$('#photoInput').onchange=async e=>{const f=e.target.files[0];if(!f)return;const img=new Image();img.src=URL.createObjectURL(f);await img.decode();const c=document.createElement('canvas');c.width=c.height=180;const x=c.getContext('2d'),s=Math.min(img.width,img.height);x.drawImage(img,(img.width-s)/2,(img.height-s)/2,s,s,0,0,180,180);state.photos[state.active]=c.toDataURL('image/jpeg',.75);URL.revokeObjectURL(img.src);store();profiles();render();e.target.value=''};store();render();
